version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    timezone: UCT
  open-pull-requests-limit: 99
  groups:
    viaduct:
      patterns:
      - "viaduct*"
    minor-patch-dependencies:
      update-types: ["minor", "patch"]
