[package]
name = "remote-settings-client"
version = "0.1.0"
authors = ["Mathieu Leplatre <mathieu@mozilla.com>", "Vishwa Patel <vpatel@mozilla.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11.0"
openssl = "0.10"
async-trait = "0.1.35"
httpmock = "0.3.5"
reqwest = { version = "0.10.0-alpha.2", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2.21", features = ["macros", "tcp"] }
signatory = { version = "0.11", features = ["ecdsa", "encoding"]}
signatory-ring = "0.11"
