[package]
name = "remote-settings-client"
version = "0.1.0"
authors = ["Mathieu Leplatre <mathieu@mozilla.com>", "Vishwa Patel <vpatel@mozilla.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
env_logger = "0.7.1"
httpmock = "0.3.5"
# cannot use tags since viaduct is not published yet  
viaduct = { git = "https://github.com/mozilla/application-services", rev = "61dcc364ac0d6d0816ab88a494bbf20d824b009b"}

[dependencies]
base64 = "0.11.0"
openssl = "0.10"
canonical_json = { path = "src/client/signatures/canonical_json" }
reqwest = { version = "0.10.0-alpha.2", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
signatory = { version = "0.11", features = ["ecdsa", "encoding"]}
signatory-ring = "0.11"
log = "0.4.0"
url = "2.1"
