[package]
name = "remote-settings-client"
version = "0.1.0"
authors = ["Mathieu Leplatre <mathieu@mozilla.com>", "Vishwa Patel <vpatel@mozilla.com>"]
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["dummy_verifier"]
openssl_verifier = ["openssl", "signatory", "signatory-ring"]
dummy_verifier = []

[dev-dependencies]
env_logger = "0.7.1"
httpmock = "0.4.2"
viaduct-reqwest = { git = "https://github.com/mozilla/application-services", rev = "61dcc364ac0d6d0816ab88a494bbf20d824b009b"}

[dependencies]
base64 = "0.11.0"
canonical_json = { path = "src/client/signatures/canonical_json" }
log = "0.4.0"
url = "2.1"
# specifying viaduct dependency from git repo since viaduct is not published yet to crates.io 
viaduct = { git = "https://github.com/mozilla/application-services", rev = "61dcc364ac0d6d0816ab88a494bbf20d824b009b"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

## openssl_verifier
openssl = { version = "0.10", optional = true }
signatory = { version = "0.11", features = ["ecdsa", "encoding"], optional = true}
signatory-ring = { version = "0.11", optional = true }

