version: 2

jobs:
  test:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - run:
          name: Build documentation
          command: cargo doc --all-features
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run tests
          command: cargo test --all
      - run:
          name: Run optional features' tests
          command: cargo test --features=ring_verifier
workflows:
  version: 2
  test:
    jobs:
      - test
